### ISSUE TITLE
`wr` accepts broken solution for `07/02`

### ISSUE THREAD

**Issue by cognivore** [mainmatter/rust-advanced-testing-workshop#4] opened 2024-03-26 17:09 UTC
# Why?

Our [broken and overly verbose solution](https://github.com/cognivore/rust-advanced-testing-workshop/blob/2f20299ebd537564d8729f29ae9a2f82a610c7ad/exercises/07_http_mocking/02_match/src/lib.rs) uses `unwrap` to get "Content-Length" header, and thus crashes in tests.

However, `wr --no-skip` is green:

```
Tue Mar 26 17:06:49:229264293 sweater@timetwister ~/github/rust-advanced-testing-workshop (main)

λ wr --no-skip


Running tests...

        🚀 (01) better_assertions - (00) intro
        🚀 (01) better_assertions - (01) std_assertions
        🚀 (01) better_assertions - (02) googletest
        🚀 (01) better_assertions - (03) eq
        🚀 (01) better_assertions - (04) options_and_results
        🚀 (01) better_assertions - (05) enums
        🚀 (01) better_assertions - (06) collections
        🚀 (01) better_assertions - (07) custom_matcher
        🚀 (01) better_assertions - (08) expect_that
        🚀 (01) better_assertions - (09) outro
        🚀 (02) snapshots - (00) intro
        🚀 (02) snapshots - (01) snapshots
        🚀 (02) snapshots - (02) storage_location
        🚀 (02) snapshots - (03) redactions
        🚀 (02) snapshots - (04) outro
        🚀 (03) mocks - (00) intro
        🚀 (03) mocks - (01) traits
        🚀 (03) mocks - (02) mockall
        🚀 (03) mocks - (03) sequences
        🚀 (03) mocks - (04) checkpoints
        🚀 (03) mocks - (05) foreign_traits
        🚀 (03) mocks - (06) outro
        🚀 (04) interlude - (00) testing_infrastructure
        🚀 (05) filesystem_isolation - (00) intro
        🚀 (05) filesystem_isolation - (01) named_tempfile
        🚀 (05) filesystem_isolation - (02) tempfile
        🚀 (05) filesystem_isolation - (03) tempdir
        🚀 (05) filesystem_isolation - (04) outro
        🚀 (06) database_isolation - (00) intro
        🚀 (06) database_isolation - (01) sqlx_test
        🚀 (07) http_mocking - (00) intro
        🚀 (07) http_mocking - (01) basics
        🚀 (07) http_mocking - (02) match
        Eternity lies ahead of us, and behind. Your path is not yet finished. 🍂

Do you want to open the next exercise, (07) http_mocking - (03) checkpoints? [y/n] n
```

# Expected outcome

`wr` will complain about no success, just as `cargo test` does.

**Comment by cognivore** [comment] 2024-03-26 17:12
Update: it accepts **no solution** for 07/03!

```
Tue Mar 26 17:11:08:187165164 sweater@timetwister ~/github/rust-advanced-testing-workshop (main)

λ wr


Running tests...

        ✅ (01) better_assertions - (00) intro (Skipped)
        ✅ (01) better_assertions - (01) std_assertions (Skipped)
        ✅ (01) better_assertions - (02) googletest (Skipped)
        ✅ (01) better_assertions - (03) eq (Skipped)
        ✅ (01) better_assertions - (04) options_and_results (Skipped)
        ✅ (01) better_assertions - (05) enums (Skipped)
        ✅ (01) better_assertions - (06) collections (Skipped)
        ✅ (01) better_assertions - (07) custom_matcher (Skipped)
        ✅ (01) better_assertions - (08) expect_that (Skipped)
        ✅ (01) better_assertions - (09) outro (Skipped)
        ✅ (02) snapshots - (00) intro (Skipped)
        ✅ (02) snapshots - (01) snapshots (Skipped)
        ✅ (02) snapshots - (02) storage_location (Skipped)
        ✅ (02) snapshots - (03) redactions (Skipped)
        ✅ (02) snapshots - (04) outro (Skipped)
        ✅ (03) mocks - (00) intro (Skipped)
        ✅ (03) mocks - (01) traits (Skipped)
        ✅ (03) mocks - (02) mockall (Skipped)
        ✅ (03) mocks - (03) sequences (Skipped)
        ✅ (03) mocks - (04) checkpoints (Skipped)
        ✅ (03) mocks - (05) foreign_traits (Skipped)
        ✅ (03) mocks - (06) outro (Skipped)
        ✅ (04) interlude - (00) testing_infrastructure (Skipped)
        ✅ (05) filesystem_isolation - (00) intro (Skipped)
        ✅ (05) filesystem_isolation - (01) named_tempfile (Skipped)
        ✅ (05) filesystem_isolation - (02) tempfile (Skipped)
        ✅ (05) filesystem_isolation - (03) tempdir (Skipped)
        ✅ (05) filesystem_isolation - (04) outro (Skipped)
        ✅ (06) database_isolation - (00) intro (Skipped)
        ✅ (06) database_isolation - (01) sqlx_test (Skipped)
        ✅ (07) http_mocking - (00) intro (Skipped)
        ✅ (07) http_mocking - (01) basics (Skipped)
        ✅ (07) http_mocking - (02) match (Skipped)
        🚀 (07) http_mocking - (03) checkpoints
        Eternity lies ahead of us, and behind. Your path is not yet finished. 🍂

Do you want to open the next exercise, (07) http_mocking - (04) outro? [y/n]
```

**Comment by cognivore** [comment] 2024-04-16 15:19
(I remember about this one)

**Comment by LukeMathWalker** [comment] 2024-08-01 08:19
Closing since I can't reproduce.

**Closed by LukeMathWalker** 2024-08-01 08:19 UTC
